# Generated by Django 2.2.16 on 2020-09-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200911_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='fax',
        ),
    ]
