# Generated by Django 2.2.16 on 2020-09-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20200911_1335"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fax",
            new_name="faxs",
        ),
    ]
