# Generated by Django 2.2.16 on 2020-09-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200911_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='faxs',
            new_name='faxs23',
        ),
    ]
