# Generated by Django 2.2.16 on 2020-09-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200911_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='test1',
            new_name='demo',
        ),
        migrations.RenameField(
            model_name='customtext',
            old_name='test2',
            new_name='phone',
        ),
    ]
