# Generated by Django 2.2.16 on 2020-09-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200911_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='demo',
            new_name='new',
        ),
    ]
