# Generated by Django 2.2.16 on 2020-09-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200923_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='test',
        ),
    ]
